version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: spotiflac_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: .
    image: spotiflac-backend:latest
    container_name: spotiflac_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0      # жёстко перезаписываем, чтобы не тянуть из .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn spotiflac_backend.main:app --host 0.0.0.0 --port 8000

volumes:
  redis_data:
